/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'logo-primary': '#2F27CE',
        'text-logo-primary': '#2F27CE',
        'white-text': '#FBFBFE',
        'white-div': '#FBFBFE',
        'sidebar-button': '#E4E7F5',
        'sidebar-text': '#082431',
        'sidebar-selected-text': '#433BFF',
        'sidebar-bg': '#F1F2F7',
        'footer-bg': '#6F6ADD',
        'meta-bg': '#E8EAED',
        'meta-button-inactive': '#D9D9D9',
        'meta-button-active': '#433BFF',
        'receita-bg': '#E8F5E9',
        'receita-highlight': '#4CAF50',
        'receita-button-active': '#4CAF50',
        'receita-button-inactive': '#D9D9D9',
        'despesa-bg': '#FFEBEE',
        'despesa-button-inactive': '#D9D9D9',
        'despesa-button-active': '#F44336',
        'categoria-bg': '#FFF3E0',
        'button-active': '#433BFF',
        'input-border': '#D9D9D9',
        'cartoes-bg': '#E3F2FD',
        'perfil-bg': '#F3E5F5',
        'button-profile-inactive': '#D9D9D9',
        'delete-button': '#F44336',
        'gray-outline': '#BDBDBD',
        'google-button-hover': '#F5F5F5',
        'theme-light': '#FFFFFF',
      },
      fontFamily: {
        'lato-black': ['Lato-Black', 'sans-serif'],
        'lato-black-i': ['Lato-Black-Italic', 'sans-serif'],
        'lato-bold': ['Lato-Bold', 'sans-serif'],
        'lato-bold-i': ['Lato-Bold-Italic', 'sans-serif'],
        'lato-italic': ['Lato-Italic', 'sans-serif'],
        'lato-light': ['Lato-Light', 'sans-serif'],
        'lato-light-i': ['Lato-Light-Italic', 'sans-serif'],
        'lato-regular': ['Lato-Regular', 'sans-serif'],
        'lato-thin': ['Lato-Thin', 'sans-serif'],
        'lato-thin-i': ['Lato-Thin-Italic', 'sans-serif'],
      }
    },
  },
  plugins: [],
}